### ISSUE TITLE
Refactor your code to conform to best practices

### ISSUE THREAD

**Issue by raskasa** [bubah/personal-website#2]
Refactor your code to conform to the best practices outlined in the [Code Guide by @mdo](http://codeguide.co/).

###### HTML

- [x] Syntax
- [x] HTML5 doctype
- [x] Language attribute
- [x] Character encoding
- [x] Internet Explorer compatibility mode
- [x] CSS and JavaScript includes
- [x] Practicality over purity
- [x] Attribute order
- [x] Boolean attributes
- [x] Reducing markup
- [x] JavaScript generated markup

###### CSS

- [x] CSS syntax
- [x] Declaration order
- [x] Media query placement
- [x] Prefixed properties
- [x] Rules with single declarations
- [x] Shorthand notation
- [x] Comments
- [x] Classes
- [x] Selectors
- [x] Organization

LINK: http://codeguide.co/

**Comment by raskasa** [comment]
@bubah Try to have one commit per checklist item.

**Comment by bubah** [comment]
Okay but for my home page I did most of it. I'll do that with other two pages.

**Comment by raskasa** [comment]
Sounds good.

**Comment by raskasa** [comment]
There are two rules under the Syntax section that cover spacing:

* Use soft tabs with two spaces—they're the only way to guarantee code renders the same in any environment.
* Nested elements should be indented once (two spaces).

I see you made the proper changes in `index.html`, but I don't see the proper spacing in `aboutme.html` and `contact.html`.

**Comment by bubah** [comment]
I updated the spacing for the aboutme and contact page. Also updated the links to the external files. Should be all set, Let me know if you see anything else.

**Comment by raskasa** [comment]
Use forward slashes instead of backward slashes:

```diff
- <link rel="stylesheet"; href="css\home.css">
+ <link rel="stylesheet"; href="css/home.css">
```

Hopefully you're still viewing your site locally by running the Python server I showed you:

```bash
$ cd C:\Dev\personal-website
$ python -m SimpleHTTPServer
```

Did you do the CSS checklist items as well?

**Comment by bubah** [comment]
I updated code with forward slashes. Yes i am viewing code locally and have completed the css check list. See the latest uploads for the css files.

**Comment by raskasa** [comment]
Hmm, I still don't see two-space indents in the CSS files and a couple of other things.  But this is good enough for now.

We can continue to work on this on the side, but we've completed the first steps.  Now we want to move on to learning Ruby on Rails.
